### ISSUE TITLE
DataStoreFactory.scenario_data_store().get("MyKey") returns keyerror

### ISSUE THREAD

**Issue by thelettermegan** [kashishm/gauge-python#16]
### Description

At the scenario level, the DataStoreFactory get command fails and returns a keyerror instead of the value previously entered. 

### Steps to reproduce
1. put a value in the Scenario level DatastoreFactory (DataStoreFactory.scenario_data_store().put(key, value)) as part of execution of a step
2. retrieve a value from the scenario level DataStoreFactory as part of a following step in the scenario (DataStoreFactory.scenario_data_store().get(key)) 

### Information that will help us debug

* Gauge version: 0.9.4
* Gauge Python plugin version (0.2.2)
* Python version  2.7.13
* `getgauge` package version, run `pip3 show getgauge` to get it: Version: 0.2.1
* OS information: OS X El Capitan 10.11.6

**Comment by brywiser** [comment]
I see the same issue as well.

**Comment by kashishm** [comment]
@thelettermegan @brywiser It's working as expected for me. Can you replicate this issue on a sample project? If so, please update the issue with specification and implementation text.

Here's my working example

**Spec**
``` markdown
Spec
====
Scenario
--------
* put
* get
```

**Impl**
``` py
from getgauge.python import step, DataStoreFactory

@step('put')
def put():
    DataStoreFactory.scenario_data_store().put('a', 'b')


@step('get')
def get():
    assert DataStoreFactory.scenario_data_store().get('a') == 'b'
```

**Comment by thelettermegan** [comment]
I was able to used the scenario_data_store().get inside the step function, but not when the step function calls a method that contains the scenario_data_store()

**Comment by brywiser** [comment]
When we implement the scenario data store using the sample setup you mention above.  It works as expected.  However, I use the suite_data_store and it works outside of the step functions.  So for example, we write our code in a page object pattern.  I call a function from the step implementation that is in another class than the actual step.  And that works, when we tried that with the scenario store, it didn't work as we expected.  Does that make sense?  I can put some sample code up if needed.

**Comment by kashishm** [comment]
@thelettermegan @brywiser It'd really help if you could provide a sample project or code snippets to replicate this issue.

**Comment by brywiser** [comment]
@kashishm Sorry for the delay.  We are still working through getting you some sample code now.  Sorry!  We got hung up in some other work here!

**Comment by thelettermegan** [comment]
Hey Kashishm, Thanks for waiting on this! I'm working with a large page object model framework and tried to replicate it here: https://github.com/thelettermegan/gauge_dataStore_keyError 

Ironically, I was unable to replicate the bug! I'm going to close this now, and if I can figure out what exactly was the issue I'll open a new one. 

Thanks again for your patience!!!
