### ISSUE TITLE
Failed to initialize project. exit status 127

### ISSUE THREAD

**Issue by berndca** [kashishm/gauge-python#3]
I'm getting an error running gauge --init python. I have installed getgauge-0.1.1. 

Please advise.
Thanks, Bernd

$ gauge --init python

	 create  manifest.json
	 create  specs
	 create  specs/example.spec
	 create  env
	 create  env/default
	 create  env/default/default.properties
	/usr/bin/env: python -u: No such file or directory

$ gauge -v

	Gauge version: 0.4.0

	Plugins
	-------
	html-report (2.1.0)
	java (0.3.4)
	python (0.1.1)

**Comment by berndca** [comment]
Changed first line in  ~/.gauge/plugins/python/0.1.1/start.py from

    #! /usr/bin/env python -u

to 

    #! /usr/bin/env python

and running gauge in a virtualenv (pyvenv) fixed the issue in Elementary OS (Ubuntu LTS 14.04).

**Comment by kashishm** [comment]
`-u` flag is just for unbuffered binary stdout and stderr, this should not fail/stop the runner.
This is a bug in runner. It happens when python executable is not present in `/usr/bin`
Could you please share the location of the python executable?
you can try creating a symlink of `python` in `/usr/bin` and refer it to python executable, this should fix the issue for now.

**Comment by berndca** [comment]
Interesting! I'm using pyenv (https://github.com/yyuu/pyenv) which changes the python path to

    /home/bernd/.pyenv/shims/python

However I understand that since I'm using the latest version of getgauge I need python 3. That would mean to either call /usr/bin/python3 or work with a virtualenv. Changing /usr/bin/python to python3 is not an option.  I ended up using a virtualenv and the path to the python executable in this context is

    /home/bernd/Downloads/gauge/s5/gauge_venv/bin/python

You should be able to reproduce the by using a virtualenv.

**Comment by berndca** [comment]
It appears that you can not pass arguments to python when using /usr/bin/env:

https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my/29620#29620

**Comment by kashishm** [comment]
Thanks for the info @berndca. I have released a new version with the fix. Run the following commands to update the plugin and package.
```
gauge --update python
pip install getgauge --upgrade
```
Follow the [docs](http://gauge-python.readthedocs.org/en/latest/faq.html#print-statements-are-getting-printed-at-the-end-of-execution), If print statements are getting printed at the end of execution.

**Comment by berndca** [comment]
Thanks! Did you consider to replace start.py with a start.sh in which PYTHONUNBUFFERED is set and the new/renamed start.py is called?

**Comment by kashishm** [comment]
There were two solutions to this issue: 
- Add start.sh which will call start.py with `PYTHONUNBUFFERED` set as env var or pass `-u` flag to `python` executable(as you suggested).
- Add a `python.properties` file with `PYTHONUNBUFFERED = 1` and let Gauge handle this while execution.

I implemented it using the second approach, but I think it would work with both the approcahes.
