### ISSUE TITLE
Failed to initialize project, exit status 1, using python 2.7 on last 2 releases

### ISSUE THREAD

**Issue by galacticgumshoe** [kashishm/gauge-python#5]
On both 0.1.3 and 0.1.2 versions of the plugin, I am getting this error when trying to initialize a new project:

Traceback (most recent call last):
  File "./start.py", line 5, in <module>
    from getgauge.impl_loader import load_impls, copy_skel_files
ImportError: cannot import name copy_skel_files
Failed to initialize project. exit status 1

System Info:
MacOS 10.11.3
Python 2.7.12
getgauge 0.0.4
Gauge 0.5.0

I've successfully installed the python plugin version 0.1.1 and it initializes the project just fine. It's only the last 2 versions that aren't working for me.

**Comment by kashishm** [comment]
Last two versions don't support `python2.*`. Could you please update to `pyhton3.*` and use the latest `getgauge` package. The latest package has some bug fixes and enhancements.

**Comment by galacticgumshoe** [comment]
OK, will do. It would be nice to indicate that in the Release notes that python 2 is no longer supported as of x release? Thanks for the reply!

**Comment by kashishm** [comment]
@galacticgumshoe Thanks for the suggestion. I have updated the documentation and release notes.

**Comment by galacticgumshoe** [comment]
Looks good, thanks @kashishm.

**Comment by galacticgumshoe** [comment]
@kashishm I finally got around to installing Python 3.5x on my Mac, and upgraded to 0.0.4 of getgauge. With a Mac, I end up with two separate versions of Python, as described here: https://docs.python.org/3/using/mac.html. In order to use Python 3 in the terminal, I have to use 'python3'. Otherwise if I just run 'python' it runs as Python 2.7. Even though getgauge supports Python 3, the latest version doesn't seem to detect Python 3 on a Mac, because I get this: 
Traceback (most recent call last):
  File "./start.py", line 4, in <module>
    assert sys.version_info > (3, 0), 'Getgauge package Requires python3 or greater. Make sure `python --version` outputs 3.x version'
AssertionError: Getgauge package Requires python3 or greater. Make sure `python --version` outputs 3.x version

I believe start.py needs to detect whether it's on a Mac, and try to use 'python3' instead of 'python'.

**Comment by kashishm** [comment]
@galacticgumshoe I agree with you on having a better mechanism of detecting `python` command in mac. I will create a separate issue for this and try to fix this in next release.

As a workaround, you can change the first line in `<user_home>/.gauge/plugins/python/<version>/start.py` from  `#! /usr/bin/env python` to `#! /usr/bin/env python3`

**Comment by galacticgumshoe** [comment]
@kashishm I tried as you described above, and it worked great. Thanks! I am not sure if this is important as well, but in the documentation, I believe I actually need to use pip3 to install getgauge, not pip??

**Comment by kashishm** [comment]
@galacticgumshoe The latest release of plugin supports python 2.7 and python 3.
