### ISSUE TITLE
Starting relative directory is always ~/.gauge/plugins/python/<version> and isn't being changed when specifying '--dir .' 

### ISSUE THREAD

**Issue by galacticgumshoe** [kashishm/gauge-python#6]
I have initialized my gauge project at ~/GitHub/sceo-test-suite on my local system. I have a docker compose file which I am running to simulate my testing environment, and I placed that in a new directory called ~/GitHub/sceo-test-suite/compose/message-pull-producer. So far I've had to "hard code" an absolute path to this file in my Python code (/Users/myuser/GitHub/sceo-test-suite/compose/message-pull-producer), which won't work if any of my other co-workers wants to clone this project and run it on their systems. I also need to promote this to a Ubuntu OpenStack server in my CICD environment to automate the system tests. So I really need relative pathing to work. For example, if I am currently in ~/GitHub/sceo-test-suite and I run 'gauge --dir . specs' I get this error when my Python code is using os.getcwd():

.IOError: [Errno 2] No such file or directory: '/Users/myuser/.gauge/plugins/python/0.1.3/compose/message-pull-producer-environment/docker-compose.yml'

You can see that my present working directory has somehow shifted from where I executed the gauge command to start in ~/.gauge/plugins/python/0.1.3. It expects then that I essentially have initialized my project in the plugin subdirectory and will always be working from there. Effectively ignoring the '--dir .' I passed in at runtime.

**Comment by kashishm** [comment]
@galacticgumshoe Thanks for logging the issue. I have released Gauge-Python [0.1.4](https://github.com/kashishm/gauge-python/releases/tag/v0.1.4) with the fix. Now the runner sets the working directory to gauge project root.

Run the following commands to update the plugin: 
```
gauge --update python
pip install --upgrade getgauge
```

**Comment by galacticgumshoe** [comment]
@kashishm I upgraded and tested it. Works great now, I can pass in '--dir .' and it properly finds my directories/files starting from project root. Thank you!
