### ISSUE TITLE
Provide a mechanism where users can specify the python version which will be used to run the specs

### ISSUE THREAD

**Issue by kashishm** [kashishm/gauge-python#7]
_From @galacticgumshoe_

In order to use Python 3 on mac, I have to use 'python3' command. Otherwise, if I just run 'python' command it runs as Python 2(default version). `Getgauge` package uses `python` command to run the tests, So it uses python 2 and mac doesn't recommend to change the default python to python3 because many Apple- or third-party software are dependent on that(https://docs.python.org/3/using/mac.html). 

There should be a mechanism where users can specify the python version which will be used to run the specs. For more details refer #5.

**Comment by galacticgumshoe** [comment]
@kashishm 👍 for this enhancement! I was just noticing that when running my specs it was running as 2.7, even though I had written everything to be compliant with 3.5! Can't wait until this is available!

**Comment by kashishm** [comment]
Implemented this enhancement in Gauge-Python [0.1.5](https://github.com/kashishm/gauge-python/releases/tag/v0.1.5). The [docs](http://gauge-python.readthedocs.io/en/latest/faq.html#use-different-version-of-python-while-running-specs) has info on how to specify a version.

Run the following commands to update the plugin: 
```
gauge --update python
pip install --upgrade getgauge
```

**Comment by galacticgumshoe** [comment]
@kashishm this latest version works well! I was able to successfully execute gauge with the 3.5 python runner after setting this in my python.properties file. Awesome job!
