### ISSUE TITLE
Installation issue - Missing api.py

### ISSUE THREAD

**Issue by akanksha4lal** [kashishm/gauge-python#9]
### Description
Every time we set up a new machine to run the gauge python, I run into issue where 
`from getgauge import api `
step fails.
We have to remove , reinstall and somehow it comes. Or manually get the getgauge files and put it there from other machine.

We follow the instructions given here : `http://gauge-python.readthedocs.io/en/latest/installation.html`

and always used pip to install the getgauge

### Steps to reproduce
1. Install getgauge
2. Install gauge python plugin
3. Run spec file

### Information that will help us debug

* Gauge version 0.7.0
* Gauge Python plugin version 0.1.7
* Python version 2.7.10
* `getgauge` package version, run `pip3 show getgauge` to get it : 0.1.7
* OS information Mac OS Sierra

**Comment by kashishm** [comment]
@akanksha4lal This might happen when `getgauge` package is missing or `pip` has installed it for `python3` and the project uses `python2.7`. 

One way to verify this would be to check if the package is present in python2.7 `site-packages`. Run the following command
```
$ python2.7
>>> from distutils.sysconfig import get_python_lib
>>> print get_python_lib()
```
And check if the `getgauge` package exists in the path printed by the above command. If not you will have to configure `pip` for `python2.7`.

**Comment by akanksha4lal** [comment]
@kashishm 
I don't have python3. There is only 2.7 version installed. Its not that `getgauge` is entirely absent, specifically api.py and validator.py are the two files which are missing. Rest of the package comes in. 
This has happened on multiple MacOS machines. Adding these files manually resolves the problem.
